### ISSUE TITLE
Broken URL 

### ISSUE THREAD

**Issue by robmarkcole** [ceos-seo/data_cube_ui#29]
The link from [here ](https://www.opendatacube.org/data-cube-installation)to [here ](https://github.com/ceos-seo/data_cube_ui/blob/master/docs/datacube_install.md)is broken

**Comment by AMA-AC** [comment]
Thanks for the input!  We're in the process of updating our documentation and will make sure to update that link as well.  I expect that it will just point [here](https://github.com/ceos-seo/data_cube_ui) and that readme file will direct users where to go from there.
