### ISSUE TITLE
Apache2 - 500 Internal Error

### ISSUE THREAD

**Issue by xxsamxx1991** [ceos-seo/data_cube_ui#32]
On every visit of the site i get the error "500 Internal Error".

The following entrys appear in "/var/log/apache2/error.log":
`[Mon Feb 11 12:40:50.022136 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]     django.setup(set_prefix=False)
[Mon Feb 11 12:40:50.022152 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "/home/datacube/Datacube/datacube_env/lib/python3.6/site-packages/django/__init__.py", line 22, in setup
[Mon Feb 11 12:40:50.022161 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Mon Feb 11 12:40:50.022178 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "/home/datacube/Datacube/datacube_env/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
[Mon Feb 11 12:40:50.022187 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]     self._setup(name)
[Mon Feb 11 12:40:50.022203 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "/home/datacube/Datacube/datacube_env/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
[Mon Feb 11 12:40:50.022212 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]     self._wrapped = Settings(settings_module)
[Mon Feb 11 12:40:50.022228 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "/home/datacube/Datacube/datacube_env/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
[Mon Feb 11 12:40:50.022237 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Mon Feb 11 12:40:50.022270 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "/home/datacube/Datacube/datacube_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
[Mon Feb 11 12:40:50.022280 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]     return _bootstrap._gcd_import(name[level:], package, level)
[Mon Feb 11 12:40:50.022296 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Mon Feb 11 12:40:50.022313 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Mon Feb 11 12:40:50.022330 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
[Mon Feb 11 12:40:50.022347 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Mon Feb 11 12:40:50.022365 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
[Mon Feb 11 12:40:50.022381 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
[Mon Feb 11 12:40:50.022398 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Mon Feb 11 12:40:50.022430 2019] [wsgi:error] [pid 4225:tid 139682675848960] [remote 132.187.202.59:53302] ModuleNotFoundError: No module named 'data_cube_ui'
`

Could someone help me to figure out the problem?

**Comment by ikselven** [comment]
Well, the last line says:
```
ModuleNotFoundError: No module named 'data_cube_ui'
```
This means, that the Python interpreter that is run by Apache is unable to find the `data_cube_ui` directory of this repository. Make sure `python-path` is configured correctly, as shown in the following section of the documentation: https://github.com/ceos-seo/data_cube_ui/blob/master/docs/ui_install.md#configuration

**Comment by xxsamxx1991** [comment]
Thank you for this good answer.

After i corrected the path for "python-path" everything is working now.
